host: 127.0.0.1
database: vehicle_detect
username: root
password: 123456

mail-server:
  username: example@mail.com
  password: 123456



spring:
  application:
    name: traffic_stat
  profiles:
    # 外置jdbc、redis
    active: jdbc,redis,mail
  jackson:
    date-format: yyyy-MM-dd HH:mm
    time-zone: GMT+8

server:
  port: 9012

# mybatis-plus配置
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: isDeleted # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
      table-underline: true #驼峰下划线映射
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  #实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.yui.traffic_stat.infrastructure.entity

logging:
  level:
    com.yui.traffic_stat.infrastructure.mapper: debug
